boiler_automation:

  automation:

    # --- Turn ON boiler when heating demand appears ---
    - alias: Boiler ON
      trigger:
        - platform: state
          entity_id: binary_sensor.heating_demand
          to: 'on'
      condition:
        - condition: state
          entity_id: input_boolean.boiler_locked
          state: 'off'
      action:
        - service: switch.turn_on
          target:
            entity_id: switch.boiler_control_switch
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.boiler_locked
        - service: timer.start
          target:
            entity_id: timer.boiler_min_on

    # --- Turn OFF boiler after min-on if no heating demand ---
    - alias: Boiler OFF after min-on
      trigger:
        - platform: event
          event_type: timer.finished
          event_data:
            entity_id: timer.boiler_min_on
      condition:
        - condition: state
          entity_id: binary_sensor.heating_demand
          state: 'off'
      action:
        - service: switch.turn_off
          target:
            entity_id: switch.boiler_control_switch
        - service: timer.start
          target:
            entity_id: timer.boiler_min_off
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.boiler_locked

    # --- Unlock boiler after min-off ---
    - alias: Unlock Boiler After Min Off
      trigger:
        - platform: event
          event_type: timer.finished
          event_data:
            entity_id: timer.boiler_min_off
      action:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.boiler_locked
